name: study_with_me
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_datetime_picker: ^1.5.1
  url_launcher: ^6.0.6
  intl: ^0.19.0
  permission_handler: ^11.1.0
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  open_file_plus: ^3.4.1
  image_picker: ^1.0.7
  photo_view: ^0.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/images/slash_screen.png
  - assets/images/registration.png
  - assets/images/login.png
  - assets/images/avatars/
  - assets/images/coin.png
  - files/

  